# Generated by Django 4.2.5 on 2024-04-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armstrong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
