# Generated by Django 4.2.5 on 2024-04-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armstrong', '0009_alter_customer_phone_number_alter_feedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
