# Generated by Django 4.2.5 on 2024-04-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armstrong', '0010_alter_feedback_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
